import { AppState, HabitItem, RandomQuest, Challenge, CollectionItem, GardenPlant, GardenDecoration } from '../types';

export const RANDOM_QUEST_POOL: Omit<RandomQuest, 'id' | 'completed' | 'dateAssigned'>[] = [
  {
    title: 'Dọn bàn học trong 10 phút',
    description: 'Xếp lại tập vở, lau sạch mặt bàn và cất bớt những món đồ không cần thiết.',
    category: 'routine',
    tip: 'Bàn học thoáng đãng giúp não bộ bớt căng thẳng và tập trung gấp đôi!',
    durationMinutes: 10,
    expReward: 60,
    seedReward: 25,
    waterDropReward: 15,
  },
  {
    title: 'Hôm nay thử đi bộ 15 phút',
    description: 'Rời bàn học, đi dạo quanh xóm hoặc leo cầu thang hít thở không khí tự nhiên.',
    category: 'health',
    tip: 'Vận động nhẹ kích thích lưu thông máu và nạp lại năng lượng cho mắt.',
    durationMinutes: 15,
    expReward: 70,
    seedReward: 30,
    waterDropReward: 20,
  },
  {
    title: 'Sắp xếp lại góc học tập & hộp bút',
    description: 'Gọt lại bút chì, gom bút bi hết mực bỏ đi và xếp gọn gàng vào hộp.',
    category: 'routine',
    tip: 'Một góc học tập ngăn nắp sẽ truyền cảm hứng học hành rất lớn!',
    durationMinutes: 10,
    expReward: 50,
    seedReward: 20,
    waterDropReward: 15,
  },
  {
    title: 'Uống 1 ly nước ấm ngay khi ngồi vào bàn',
    description: 'Rót một cốc nước ấm, nhấp từng ngụm chậm rãi trước khi bắt đầu học.',
    category: 'health',
    tip: 'Nước ấm đánh thức các giác quan và làm dịu cổ họng.',
    durationMinutes: 3,
    expReward: 40,
    seedReward: 15,
    waterDropReward: 25,
  },
  {
    title: 'Gửi lời nhắn động viên một người bạn',
    description: 'Nhắn một câu chúc thi tốt, hỏi thăm hoặc cảm ơn bạn bè, người thân.',
    category: 'mindfulness',
    tip: 'Gieo hạt mầm yêu thương sẽ nhận lại sự ấm áp trong tâm hồn.',
    durationMinutes: 5,
    expReward: 55,
    seedReward: 25,
    waterDropReward: 20,
  },
  {
    title: 'Tắt màn hình trước khi ngủ 20 phút',
    description: 'Để điện thoại xa tầm tay, nằm nhắm mắt hoặc nghe nhạc êm dịu.',
    category: 'routine',
    tip: 'Ánh sáng xanh ức chế melatonin, kiêng 20 phút giúp bạn ngủ sâu hơn.',
    durationMinutes: 20,
    expReward: 80,
    seedReward: 35,
    waterDropReward: 25,
  },
  {
    title: 'Tập 10 nhịp thở sâu & giãn cơ vai',
    description: 'Hít sâu bằng mũi 4 giây, giữ 4 giây, thở ra 6 giây kết hợp xoay khớp vai.',
    category: 'mindfulness',
    tip: 'Giải phóng áp lực tích tụ ở cổ và vai khi ngồi học lâu.',
    durationMinutes: 5,
    expReward: 45,
    seedReward: 20,
    waterDropReward: 15,
  },
  {
    title: 'Viết ra 3 điều biết ơn hôm nay',
    description: 'Ghi nhanh 3 điều nhỏ bé khiến bạn mỉm cười trong ngày ra sổ hoặc ghi chú.',
    category: 'mindfulness',
    tip: 'Lòng biết ơn biến những điều bình dị thành hạnh phúc to lớn.',
    durationMinutes: 5,
    expReward: 60,
    seedReward: 25,
    waterDropReward: 20,
  },
];

export const INITIAL_HABITS: HabitItem[] = [
  {
    id: 'habit_water',
    title: 'Uống đủ 2L nước mỗi ngày',
    category: 'health',
    streak: 3,
    completedToday: false,
    expReward: 50,
    seedReward: 20,
    waterDropReward: 40,
    type: 'counter',
    currentCount: 3,
    targetCount: 8,
    unit: 'ly',
    iconName: 'Droplets',
    note: 'Mỗi ly 250ml giúp cơ thể tươi tỉnh và da dẻ hồng hào',
    timeOfDay: 'anytime',
  },
  {
    id: 'habit_desk',
    title: 'Dọn bàn học ngăn nắp',
    category: 'routine',
    streak: 2,
    completedToday: false,
    expReward: 40,
    seedReward: 20,
    waterDropReward: 10,
    type: 'simple',
    iconName: 'Sparkles',
    note: 'Dọn sạch giấy rác, xếp sách vở ngăn nắp sau khi học',
    timeOfDay: 'evening',
  },
  {
    id: 'habit_study',
    title: 'Học tập tập trung 25 phút',
    category: 'study',
    streak: 4,
    completedToday: false,
    expReward: 60,
    seedReward: 25,
    waterDropReward: 15,
    type: 'simple',
    iconName: 'Timer',
    note: 'Phương pháp Pomodoro: không lướt mạng xã hội',
    timeOfDay: 'anytime',
  },
  {
    id: 'habit_read',
    title: 'Đọc 10 trang sách hữu ích',
    category: 'study',
    streak: 1,
    completedToday: false,
    expReward: 45,
    seedReward: 20,
    waterDropReward: 10,
    type: 'simple',
    iconName: 'BookOpen',
    note: 'Đọc sách kỹ năng, văn học hoặc kiến thức mới',
    timeOfDay: 'afternoon',
  },
  {
    id: 'habit_exercise',
    title: 'Vận động & giãn cơ 15 phút',
    category: 'health',
    streak: 2,
    completedToday: false,
    expReward: 50,
    seedReward: 25,
    waterDropReward: 15,
    type: 'simple',
    iconName: 'Activity',
    note: 'Đi bộ, nhảy dây hoặc vươn vai thư giãn',
    timeOfDay: 'afternoon',
  },
  {
    id: 'habit_prep',
    title: 'Chuẩn bị đồ cho ngày mai',
    category: 'routine',
    streak: 5,
    completedToday: false,
    expReward: 35,
    seedReward: 15,
    waterDropReward: 10,
    type: 'simple',
    iconName: 'Backpack',
    note: 'Soạn cặp, kiểm tra bài tập và quần áo sẵn sàng',
    timeOfDay: 'evening',
  },
  {
    id: 'habit_sleep',
    title: 'Ngủ trước 23:00',
    category: 'health',
    streak: 1,
    completedToday: false,
    expReward: 70,
    seedReward: 30,
    waterDropReward: 20,
    type: 'simple',
    iconName: 'Moon',
    note: 'Giúp cơ thể tái tạo năng lượng cho ngày mới tươi sáng',
    timeOfDay: 'evening',
  },
];

export const INITIAL_CHALLENGES: Challenge[] = [
  {
    id: 'challenge_desk_7d',
    title: '7 ngày dọn bàn học ngăn nắp',
    description: 'Giữ góc học tập luôn tinh tươm trong 7 ngày liên tiếp để rèn tính gọn gàng.',
    durationDays: 7,
    currentDay: 2,
    completed: false,
    claimed: false,
    badgeId: 'badge_tidy_desk',
    rewardSeeds: 150,
    rewardDrops: 80,
    rewardItemName: 'Nón Rơm Mầm Xinh 🌱👒',
    checkins: [true, true, false, false, false, false, false],
    icon: 'Sparkles',
  },
  {
    id: 'challenge_reading_5d',
    title: '5 ngày đọc sách mở mang tri thức',
    description: 'Mỗi ngày đọc ít nhất 10 trang sách để hình thành tình yêu con chữ.',
    durationDays: 5,
    currentDay: 1,
    completed: false,
    claimed: false,
    badgeId: 'badge_bookworm',
    rewardSeeds: 120,
    rewardDrops: 60,
    rewardItemName: 'Kính Trí Thức Bác Học 👓',
    checkins: [true, false, false, false, false],
    icon: 'BookOpen',
  },
  {
    id: 'challenge_sleep_7d',
    title: '7 ngày ngủ đúng giờ (trước 23h)',
    description: 'Nói không với thức khuya, bảo vệ sức khỏe và làn da tươi tắn.',
    durationDays: 7,
    currentDay: 1,
    completed: false,
    claimed: false,
    badgeId: 'badge_early_sleeper',
    rewardSeeds: 180,
    rewardDrops: 100,
    rewardItemName: 'Mũ Ngủ Trăng Sao 🌙',
    checkins: [true, false, false, false, false, false, false],
    icon: 'Moon',
  },
  {
    id: 'challenge_water_14d',
    title: '14 ngày cấp nước cơ thể đủ 2L',
    description: 'Tưới mát cho bản thân và Bé Mầm với 8 ly nước mỗi ngày.',
    durationDays: 14,
    currentDay: 3,
    completed: false,
    claimed: false,
    badgeId: 'badge_hydro_master',
    rewardSeeds: 250,
    rewardDrops: 200,
    rewardItemName: 'Bình Tưới Nước Mạ Vàng ✨💧',
    checkins: [true, true, true, false, false, false, false, false, false, false, false, false, false, false],
    icon: 'Droplets',
  },
  {
    id: 'challenge_transform_30d',
    title: '30 ngày Mầm Nhỏ biến hình',
    description: 'Chăm sóc đều đặn 30 ngày để Bé Mầm tiến hóa thành Thụ Thần Hoàng Kim!',
    durationDays: 30,
    currentDay: 4,
    completed: false,
    claimed: false,
    badgeId: 'badge_legendary_tree',
    rewardSeeds: 500,
    rewardDrops: 300,
    rewardItemName: 'Hào Quang Rực Rỡ Hoàng Kim 🌟',
    checkins: Array.from({ length: 30 }, (_, i) => i < 4),
    icon: 'TreePine',
  },
];

export const INITIAL_COLLECTIONS: CollectionItem[] = [
  // Characters & Stages
  {
    id: 'stage_seed',
    type: 'character_stage',
    name: 'Hạt Mầm Ngái Ngủ',
    description: 'Hạt mầm bé xíu vùi mình dưới lớp đất tơi xốp, đang mơ về bầu trời xanh.',
    unlocked: true,
    unlockedAt: '2026-10-01',
    icon: '🌰',
    rarity: 'common',
  },
  {
    id: 'stage_sprout',
    type: 'character_stage',
    name: 'Mầm Xanh Tò Mò',
    description: 'Hai chiếc lá non đầu tiên nhú lên đón ánh mặt trời, đôi mắt tròn xoe khám phá.',
    unlocked: true,
    unlockedAt: '2026-10-02',
    icon: '🌱',
    rarity: 'common',
  },
  {
    id: 'stage_sapling',
    type: 'character_stage',
    name: 'Bé Chồi Tràn Năng Lượng',
    description: 'Cành lá xanh mướt, thích nhún nhảy theo nhịp điệu mỗi khi bạn hoàn thành việc.',
    unlocked: false,
    icon: '🌿',
    rarity: 'rare',
  },
  {
    id: 'stage_young_tree',
    type: 'character_stage',
    name: 'Cây Non Tự Tin',
    description: 'Thân cây cứng cáp, bắt đầu nở những nụ hoa thơm ngát tượng trưng cho sự kiên trì.',
    unlocked: false,
    icon: '🪴',
    rarity: 'epic',
  },
  {
    id: 'stage_golden_tree',
    type: 'character_stage',
    name: 'Thụ Thần Hoàng Kim',
    description: 'Cây cổ thụ tỏa ánh hào quang ấm áp, biểu tượng của người làm chủ thói quen bền bỉ.',
    unlocked: false,
    icon: '🌳',
    rarity: 'legendary',
  },

  // Plants in garden
  {
    id: 'plant_clover',
    type: 'plant',
    name: 'Cỏ Ba Lá May Mắn',
    description: 'Đem lại sự vui tươi và vận may ngọt ngào mỗi sáng mai.',
    unlocked: true,
    unlockedAt: '2026-10-01',
    icon: '☘️',
    rarity: 'common',
  },
  {
    id: 'plant_sunflower',
    type: 'plant',
    name: 'Hoa Hướng Dương Rạng Rỡ',
    description: 'Luôn hướng về mặt trời với tinh thần lạc quan không gì cản nổi.',
    unlocked: true,
    unlockedAt: '2026-10-03',
    icon: '🌻',
    rarity: 'rare',
  },
  {
    id: 'plant_lotus',
    type: 'plant',
    name: 'Hoa Sen An Nhiên',
    description: 'Tượng trưng cho sự tĩnh tâm, học tập sâu lắng và kiên định.',
    unlocked: false,
    icon: '🪷',
    rarity: 'rare',
  },
  {
    id: 'plant_cactus',
    type: 'plant',
    name: 'Xương Rồng Kiên Cường',
    description: 'Nhắc nhở ta vững vàng trước mọi thử thách và kỳ thi khó.',
    unlocked: true,
    unlockedAt: '2026-10-02',
    icon: '🌵',
    rarity: 'common',
  },
  {
    id: 'plant_magic_bean',
    type: 'plant',
    name: 'Cây Đậu Thần Vươn Cao',
    description: 'Cây leo thần kỳ vươn tới những ước mơ và mục tiêu học tập lớn lao.',
    unlocked: false,
    icon: '🎋',
    rarity: 'epic',
  },

  // Companion Pets
  {
    id: 'pet_snail',
    type: 'pet',
    name: 'Bé Ốc Sên Chăm Chỉ',
    description: 'Dù đi chậm nhưng không bao giờ bỏ cuộc. Luôn bên cạnh động viên bạn.',
    unlocked: true,
    unlockedAt: '2026-10-01',
    icon: '🐌',
    rarity: 'common',
  },
  {
    id: 'pet_bee',
    type: 'pet',
    name: 'Chú Ong Thợ Cần Mẫn',
    description: 'Bay quanh thụ phấn cho khu vườn và tích lũy hạt giống mỗi giờ học chăm.',
    unlocked: false,
    icon: '🐝',
    rarity: 'rare',
  },
  {
    id: 'pet_bird',
    type: 'pet',
    name: 'Chim Sâu Vui Vẻ',
    description: 'Hót ríu rít mỗi sớm mai nhắc nhở bạn uống nước và vươn vai.',
    unlocked: false,
    icon: '🐦',
    rarity: 'rare',
  },
  {
    id: 'pet_butterfly',
    type: 'pet',
    name: 'Bướm Ánh Dương',
    description: 'Đậu nhẹ lên vai Bé Mầm, mang theo luồng sinh khí tươi tắn.',
    unlocked: false,
    icon: '🦋',
    rarity: 'epic',
  },

  // Accessories
  {
    id: 'hat_straw',
    type: 'accessory',
    name: 'Nón Rơm Mầm Xinh',
    description: 'Chiếc nón rơm che nắng xinh xắn giúp Bé Mầm không sợ nắng gắt.',
    unlocked: true,
    unlockedAt: '2026-10-02',
    icon: '👒',
    rarity: 'common',
  },
  {
    id: 'hat_glasses',
    type: 'accessory',
    name: 'Kính Trí Thức Bác Học',
    description: 'Kính gọng tròn siêu ngầu giúp tăng 200% độ tập trung khi ngồi vào bàn học.',
    unlocked: false,
    icon: '👓',
    rarity: 'rare',
  },
  {
    id: 'hat_nightcap',
    type: 'accessory',
    name: 'Mũ Ngủ Trăng Sao',
    description: 'Mũ ngủ mềm mại màu xanh thẫm, gắn ngôi sao vàng lấp lánh.',
    unlocked: false,
    icon: '🌙',
    rarity: 'rare',
  },
  {
    id: 'acc_flower_bow',
    type: 'accessory',
    name: 'Nơ Hoa Tươi Tắn',
    description: 'Bông hoa nhỏ cài bên má cực kỳ dễ thương.',
    unlocked: true,
    unlockedAt: '2026-10-01',
    icon: '🌸',
    rarity: 'common',
  },
  {
    id: 'acc_backpack',
    type: 'accessory',
    name: 'Balo Đi Học Mini',
    description: 'Balo nhỏ xinh đựng đầy bút chì và hạt mầm may mắn.',
    unlocked: false,
    icon: '🎒',
    rarity: 'epic',
  },

  // Badges
  {
    id: 'badge_starter',
    type: 'badge',
    name: 'Bước Đầu Nảy Mầm',
    description: 'Hoàn thành ngày đầu tiên cùng ứng dụng Mầm Nhỏ.',
    unlocked: true,
    unlockedAt: '2026-10-01',
    icon: '🌱',
    rarity: 'common',
  },
  {
    id: 'badge_tidy_desk',
    type: 'badge',
    name: 'Góc Học Tập Gọn Gàng',
    description: 'Hoàn thành thử thách 7 ngày dọn bàn học ngăn nắp.',
    unlocked: false,
    icon: '✨',
    rarity: 'rare',
  },
  {
    id: 'badge_bookworm',
    type: 'badge',
    name: 'Mọt Sách Chăm Chỉ',
    description: 'Đọc sách 5 ngày liên tiếp.',
    unlocked: false,
    icon: '📖',
    rarity: 'rare',
  },
  {
    id: 'badge_hydro_master',
    type: 'badge',
    name: 'Thần Nước Đầy Sức Sống',
    description: 'Uống đủ 2L nước mỗi ngày trong 14 ngày.',
    unlocked: false,
    icon: '🌊',
    rarity: 'epic',
  },
];

export const INITIAL_DECORATIONS: GardenDecoration[] = [
  {
    id: 'deco_lantern',
    name: 'Đèn Lồng Đom Đóm',
    icon: '🏮',
    description: 'Tỏa ánh sáng ấm áp lung linh cho khu vườn khi trời về đêm.',
    costSeeds: 80,
    owned: true,
    placedOnPlot: 0,
  },
  {
    id: 'deco_bench',
    name: 'Ghế Gỗ Đọc Sách',
    icon: '🪑',
    description: 'Nơi ngồi nghỉ ngơi nhâm nhi cốc trà sau giờ học căng thẳng.',
    costSeeds: 120,
    owned: false,
  },
  {
    id: 'deco_pond',
    name: 'Hồ Nước Cá Koi Mini',
    icon: '🏞️',
    description: 'Mặt nước trong vắt phản chiếu trời mây, mang lại cảm giác bình yên.',
    costSeeds: 200,
    owned: false,
  },
  {
    id: 'deco_windchime',
    name: 'Chuông Gió Tre Yên Bình',
    icon: '🎐',
    description: 'Tiếng kêu lách cách êm tai mỗi khi có cơn gió mát thoảng qua.',
    costSeeds: 90,
    owned: false,
  },
  {
    id: 'deco_birdhouse',
    name: 'Tổ Chim Nhỏ Xinh',
    icon: '🏡',
    description: 'Ngôi nhà gỗ ấm cúng đón những chú chim sâu ghé thăm khu vườn.',
    costSeeds: 110,
    owned: false,
  },
];

export const INITIAL_PLANTS: (GardenPlant | null)[] = [
  {
    id: 'plant_1',
    plotIndex: 0,
    plantType: 'plant_clover',
    name: 'Cỏ Ba Lá May Mắn',
    plantedAt: '2026-10-02',
    stage: 'bloomed',
    waterCount: 3,
    waterNeeded: 3,
    color: '#4CAF50',
    harvestReady: true,
    yieldSeeds: 35,
  },
  {
    id: 'plant_2',
    plotIndex: 1,
    plantType: 'plant_sunflower',
    name: 'Hoa Hướng Dương Rạng Rỡ',
    plantedAt: '2026-10-03',
    stage: 'growing',
    waterCount: 2,
    waterNeeded: 4,
    color: '#FFB300',
    harvestReady: false,
    yieldSeeds: 60,
  },
  {
    id: 'plant_3',
    plotIndex: 2,
    plantType: 'plant_cactus',
    name: 'Xương Rồng Kiên Cường',
    plantedAt: '2026-10-04',
    stage: 'sprout',
    waterCount: 1,
    waterNeeded: 2,
    color: '#2E7D32',
    harvestReady: false,
    yieldSeeds: 40,
  },
  null,
  null,
  null,
];

export const INITIAL_STATE: AppState = {
  sprout: {
    name: 'Bé Mầm',
    level: 3,
    exp: 140,
    expNeeded: 250,
    mood: 'happy',
    waterLevel: 80,
    sunLevel: 85,
    loveLevel: 90,
    stageId: 'stage_sprout',
    equippedHat: 'hat_straw',
    equippedAccessory: 'acc_flower_bow',
    unlockedCostumes: ['hat_straw', 'acc_flower_bow'],
  },
  seeds: 185,
  waterDrops: 140,
  habits: INITIAL_HABITS,
  currentRandomQuest: {
    id: 'quest_today_1',
    ...RANDOM_QUEST_POOL[0],
    completed: false,
    dateAssigned: new Date().toISOString().slice(0, 10),
  },
  gardenPlots: INITIAL_PLANTS,
  decorations: INITIAL_DECORATIONS,
  history: [
    {
      id: 'h_1',
      date: '2026-10-02',
      time: '07:30',
      action: 'Hoàn thành',
      habitTitle: 'Uống 1 ly nước ấm buổi sáng',
      category: 'health',
      seedsGained: 20,
      expGained: 40,
    },
    {
      id: 'h_2',
      date: '2026-10-02',
      time: '21:15',
      action: 'Hoàn thành',
      habitTitle: 'Dọn bàn học ngăn nắp',
      category: 'routine',
      seedsGained: 20,
      expGained: 40,
    },
    {
      id: 'h_3',
      date: '2026-10-03',
      time: '15:20',
      action: 'Hoàn thành',
      habitTitle: 'Học tập tập trung 25 phút',
      category: 'study',
      seedsGained: 25,
      expGained: 60,
    },
    {
      id: 'h_4',
      date: '2026-10-03',
      time: '22:45',
      action: 'Hoàn thành',
      habitTitle: 'Ngủ trước 23:00',
      category: 'health',
      seedsGained: 30,
      expGained: 70,
    },
    {
      id: 'h_5',
      date: '2026-10-04',
      time: '08:10',
      action: 'Hoàn thành',
      habitTitle: 'Chuẩn bị đồ cho ngày mai',
      category: 'routine',
      seedsGained: 15,
      expGained: 35,
    },
  ],
  reflections: {
    '2026-10-03': {
      date: '2026-10-03',
      note: 'Hôm nay mình đã dọn bàn sạch bóng, cảm giác ngồi vào học rất nhẹ nhõm và tràn trề động lực!',
      mood: 'proud',
    },
  },
  challenges: INITIAL_CHALLENGES,
  collections: INITIAL_COLLECTIONS,
  lastLoginDate: new Date().toISOString().slice(0, 10),
  soundEnabled: true,
};

const STORAGE_KEY = 'mam_nho_app_state_v1';

export function loadAppState(): AppState {
  if (typeof window === 'undefined') return INITIAL_STATE;
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return INITIAL_STATE;
    const parsed = JSON.parse(raw);
    return { ...INITIAL_STATE, ...parsed };
  } catch (err) {
    console.error('Failed to load state from localStorage', err);
    return INITIAL_STATE;
  }
}

export function saveAppState(state: AppState): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  } catch (err) {
    console.error('Failed to save state to localStorage', err);
  }
}

export function getRandomQuest(currentId?: string): RandomQuest {
  const filtered = RANDOM_QUEST_POOL.filter((q) => q.title !== currentId);
  const choice = filtered[Math.floor(Math.random() * filtered.length)] || RANDOM_QUEST_POOL[0];
  return {
    id: 'quest_' + Date.now(),
    ...choice,
    completed: false,
    dateAssigned: new Date().toISOString().slice(0, 10),
  };
}
